---
- name: Set up prerequisites
  hosts: local
  roles:
    - prerequisites

- name: Set up PostgreSQL
  hosts: local
  become: yes
  roles:
    - postgresql
  vars_files:
    - vars/postgresql.yml

- name: Set up Redis
  hosts: local
  roles:
    - redis

- name: Set up SDKMAN
  hosts: local
  roles:
    - role: sdkman
      sdkman_install_packages:
        - { candidate: gradle, version: '5.2' }
        - { candidate: java, version: '11.0.2-open' }
        - { candidate: kotlin, version: '1.3.21' }

- name: Set up CredentialRegistry
  hosts: local
  roles:
    - credential-registry

- name: Set up Gremlin Server
  hosts: local
  roles:
    - gremlin-server

- name: Set up Gremlin Console
  hosts: local
  roles:
    - gremlin-console

- name: Set up gremlin-cer
  hosts: local
  roles:
    - gremlin-cer
